# Generated by Django 5.1.6 on 2025-02-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Empresa:')),
                ('host', models.CharField(max_length=100, verbose_name='IP Host:')),
                ('puerto', models.CharField(default=5432, max_length=4, verbose_name='Puerto de Conexion:')),
                ('nombre_db', models.CharField(default='HIDROSGC', max_length=100, verbose_name='Nombre DataBase:')),
                ('usuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'hidrologicas',
                'verbose_name_plural': 'hidrologicas',
                'db_table': 'hidrologicas',
            },
        ),
    ]
