# Generated by Django 5.1.6 on 2025-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultashidrosgc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contraseña',
            field=models.CharField(max_length=128, verbose_name='Contraseña:'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuario',
            field=models.CharField(max_length=100, verbose_name='Nombre de Usuario:'),
        ),
    ]
