# Generated by Django 5.1.6 on 2025-02-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultashidrosgc', '0002_alter_empresa_contraseña_alter_empresa_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, verbose_name='R.I.F o C.I')),
                ('numero_contrato', models.CharField(max_length=100, verbose_name='Número de Contrato')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('empresa_id', models.IntegerField(verbose_name='ID de la Empresa')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Consulta')),
            ],
            options={
                'verbose_name': 'Resultado de Consulta',
                'verbose_name_plural': 'Resultados de Consultas',
            },
        ),
    ]
