# Generated by Django 5.1.6 on 2025-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultashidrosgc', '0003_resultadoconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoconsulta',
            name='deudatotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Deuda Total'),
        ),
        migrations.AddField(
            model_name='resultadoconsulta',
            name='fechasituacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Situación'),
        ),
        migrations.AddField(
            model_name='resultadoconsulta',
            name='situacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situación'),
        ),
    ]
